#!/bin/bash
A=' 00_A.com 00_B.com 10_A.com 10_B.com 10_C.com 10_D.com 11_A.com 11_B.com 20_A.com 20_B.com 20_C.com 20_D.com 21_A.com 21_B.com 21_C.com 21_D.com 22_A.com 22_B.com 30_A.com 30_B.com 30_C.com 30_D.com 31_A.com 31_B.com 31_C.com 31_D.com 32_A.com 32_B.com 32_C.com 32_D.com 33_A.com 33_B.com 40_A.com 40_B.com 40_C.com 40_D.com 41_A.com 41_B.com 41_C.com 41_D.com '
B=' 00_A.wfn 00_B.wfn 10_A.wfn 10_B.wfn 10_C.wfn 10_D.wfn 11_A.wfn 11_B.wfn 20_A.wfn 20_B.wfn 20_C.wfn 20_D.wfn 21_A.wfn 21_B.wfn 21_C.wfn 21_D.wfn 22_A.wfn 22_B.wfn 30_A.wfn 30_B.wfn 30_C.wfn 30_D.wfn 31_A.wfn 31_B.wfn 31_C.wfn 31_D.wfn 32_A.wfn 32_B.wfn 32_C.wfn 32_D.wfn 33_A.wfn 33_B.wfn 40_A.wfn 40_B.wfn 40_C.wfn 40_D.wfn 41_A.wfn 41_B.wfn 41_C.wfn 41_D.wfn '
for a in $A 
 do 
/home/bruns/programas/chemistry/gaussian/g09/g09 $a 
done 
sed -i 's/NUCLEI/NUCLEI   B3LYP/g' *.wfn
for b in $B 
 do 
/usr/local/AIMAll/aimqb.ish -nogui -nproc=8 -encomp=4 $b 
done 
