#!/bin/bash
A=' 42_A.com 42_B.com 42_C.com 42_D.com 43_A.com 43_B.com 43_C.com 43_D.com 44_A.com 44_B.com 50_A.com 50_B.com 50_C.com 50_D.com 51_A.com 51_B.com 51_C.com 51_D.com 52_A.com 52_B.com 52_C.com 52_D.com 53_A.com 53_B.com 53_C.com 53_D.com 54_A.com 54_B.com 54_C.com 54_D.com 55_A.com 55_B.com 60_A.com 60_B.com 60_C.com 60_D.com 61_A.com 61_B.com 61_C.com '
B=' 42_A.wfn 42_B.wfn 42_C.wfn 42_D.wfn 43_A.wfn 43_B.wfn 43_C.wfn 43_D.wfn 44_A.wfn 44_B.wfn 50_A.wfn 50_B.wfn 50_C.wfn 50_D.wfn 51_A.wfn 51_B.wfn 51_C.wfn 51_D.wfn 52_A.wfn 52_B.wfn 52_C.wfn 52_D.wfn 53_A.wfn 53_B.wfn 53_C.wfn 53_D.wfn 54_A.wfn 54_B.wfn 54_C.wfn 54_D.wfn 55_A.wfn 55_B.wfn 60_A.wfn 60_B.wfn 60_C.wfn 60_D.wfn 61_A.wfn 61_B.wfn 61_C.wfn '
for a in $A 
 do 
/home/bruns/programas/chemistry/gaussian/g09/g09 $a 
done 
sed -i 's/NUCLEI/NUCLEI   B3LYP/g' *.wfn
for b in $B 
 do 
/usr/local/AIMAll/aimqb.ish -nogui -nproc=8 -encomp=4 $b 
done 
